services:
  chrispiz:
    build: .
    container_name: chrispiz
    restart: unless-stopped
    expose:
      - "4321"
    networks:
      - caddy
    secrets:
      - spotify_client_id
      - spotify_client_secret
      - spotify_refresh_token

networks:
  caddy:
    external: true
    name: n8n-docker-caddy_default

secrets:
  spotify_client_id:
    file: ./secrets/spotify_client_id
  spotify_client_secret:
    file: ./secrets/spotify_client_secret
  spotify_refresh_token:
    file: ./secrets/spotify_refresh_token
